name: deploy-app

on:
  push:
    branches:
      - main
      - feature-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy App
        run: echo "Deploy app executed successfully!"

